from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Callable

from openai import OpenAI

from agent_runtime.common import load_runtime_env_files
from agent_runtime.core.manifest_models import (
    resolve_manifest_embedding_profile,
    resolve_manifest_llm_profile,
)
from agent_runtime.memory.embeddings import EmbeddingClient
from agent_runtime.registry.skill_registry import AgentRegistry
from subagents.rag.core.markdown_loader import load_markdown_documents
from subagents.rag.core.retrieval import build_knowledge_index, write_knowledge_index


def prepare_rag_index(
    *,
    root: Path,
    output: Path,
    overwrite: bool = False,
    with_summary: bool = True,
    summary_callable: Callable[[str], str] | None = None,
) -> Path:
    output = output.expanduser()
    if not output.is_absolute():
        output = root / output
    if output.exists() and not overwrite:
        return output
    manifest = AgentRegistry(subagents_root=root / "subagents").get("rag")
    knowledge_paths = _knowledge_paths(runtime_root=root, manifest=manifest)
    if not knowledge_paths:
        raise FileNotFoundError("No Markdown files found under RAG data roots.")
    documents = load_markdown_documents(knowledge_paths)
    if not documents:
        raise ValueError("No readable text found in RAG Markdown files.")
    if with_summary and summary_callable is None:
        summary_callable = _summary_callable_from_manifest(manifest)
    index = build_knowledge_index(
        documents=documents,
        embedding_client=_embedding_client_from_manifest(manifest),
        summary_callable=summary_callable if with_summary else None,
    )
    return write_knowledge_index(index, output)


def write_rag_env_file(*, root: Path, index_path: Path, env_file: Path) -> Path:
    env_file = env_file.expanduser()
    if not env_file.is_absolute():
        env_file = root / env_file
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(
        "\n".join(
            [
                "# Generated by uv run agentweave-prepare-rag.",
                "# Loaded automatically by AgentWeave server and Streamlit startup.",
                f"RAG_INDEX_PATH={index_path.resolve()}",
                f"EMBEDDING_CLIENT_TIMEOUT={os.getenv('EMBEDDING_CLIENT_TIMEOUT', '60')}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return env_file


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare RAG local knowledge index.")
    parser.add_argument("--root", default=".", help="AgentWeave backend project root.")
    parser.add_argument(
        "--output",
        default=".agentweave/rag_index.json",
        help="RAG JSON index output path.",
    )
    parser.add_argument("--overwrite", action="store_true", help="Replace existing index file.")
    parser.add_argument(
        "--env-file",
        default=".agentweave/rag.env",
        help="Env file to write with RAG_INDEX_PATH.",
    )
    parser.add_argument(
        "--no-env-file",
        action="store_true",
        help="Prepare the index without writing a runtime env file.",
    )
    parser.add_argument(
        "--no-summary",
        action="store_true",
        help="Prepare the index without calling an LLM for summary fields.",
    )
    args = parser.parse_args()
    root = Path(args.root).resolve()
    load_runtime_env_files(root)
    os.environ.setdefault("EMBEDDING_CLIENT_TIMEOUT", "60")
    output = prepare_rag_index(
        root=root,
        output=Path(args.output),
        overwrite=bool(args.overwrite),
        with_summary=not bool(args.no_summary),
    )
    print(f"prepared={output}")
    if not args.no_env_file:
        env_file = write_rag_env_file(
            root=root,
            index_path=output,
            env_file=Path(args.env_file),
        )
        print(f"env_file={env_file}")
    print("next=uv run streamlit run app.py")


def _embedding_client_from_manifest(manifest) -> EmbeddingClient:
    return EmbeddingClient(resolve_manifest_embedding_profile(manifest))


def _knowledge_paths(*, runtime_root: Path, manifest) -> list[Path]:
    roots = manifest.data.roots if manifest is not None and manifest.data.roots else ["subagents/rag/data"]
    globs = manifest.data.globs if manifest is not None and manifest.data.globs else ["*.md"]
    paths: list[Path] = []
    for raw_root in roots:
        base = Path(raw_root)
        if not base.is_absolute():
            base = runtime_root / base
        for pattern in globs:
            paths.extend(path for path in base.glob(pattern) if path.is_file())
    return sorted(set(paths), key=lambda path: str(path))


def _summary_callable_from_manifest(manifest) -> Callable[[str], str]:
    profile = resolve_manifest_llm_profile(
        manifest,
        api_key=os.getenv("RAG_SUMMARY_API_KEY") or None,
    )
    client = OpenAI(
        base_url=profile.base_url,
        api_key=profile.api_key,
        timeout=float(os.getenv("RAG_SUMMARY_CLIENT_TIMEOUT", "60")),
        max_retries=int(os.getenv("RAG_SUMMARY_CLIENT_MAX_RETRIES", "2")),
    )
    max_tokens = max(
        1,
        min(1024, int(os.getenv("RAG_SUMMARY_MAX_TOKENS", str(profile.max_tokens or 1024)))),
    )
    extra_body = _summary_extra_body(profile.model_name)

    def call(prompt: str) -> str:
        response = client.chat.completions.create(
            model=profile.model_name,
            messages=[
                {
                    "role": "system",
                    "content": "你是知识库摘要生成器，只基于输入内容生成中文摘要。",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            max_tokens=max_tokens,
            extra_body=extra_body,
        )
        return _clean_summary_output(response.choices[0].message.content or "")

    return call


def _summary_extra_body(model_name: str) -> dict[str, object]:
    raw_extra = os.getenv("RAG_SUMMARY_EXTRA_BODY", "").strip()
    if raw_extra:
        try:
            payload = json.loads(raw_extra)
            return payload if isinstance(payload, dict) else {}
        except json.JSONDecodeError:
            return {}
    lowered = model_name.lower()
    if "qwen" in lowered or "thinking" in lowered:
        return {"chat_template_kwargs": {"enable_thinking": False}}
    return {}


def _clean_summary_output(text: str) -> str:
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"^\s*(思考过程|推理过程|思考|分析)\s*[:：].*?(?=\n{2,}|$)", "", text, flags=re.DOTALL)
    return text.strip()


if __name__ == "__main__":
    main()
