"""CLI for preparing local Text2SQL SQLite databases from CSV fixtures."""

from __future__ import annotations

import argparse
import csv
import sqlite3
from pathlib import Path
from typing import Any

from agent_runtime.shared.database import quote_identifier
from agent_runtime.shared.manifest import load_subagent_manifest
from subagents.text2sql.core.domain_catalog import Text2SQLDomainCatalog


def prepare_sqlite_database(*, root: Path, output: Path, overwrite: bool = False) -> Path:
    """Build a local SQLite database from Text2SQL domain CSV files."""
    manifest = load_subagent_manifest(root, "text2sql")
    tables = manifest_csv_tables(root=root, manifest=manifest)
    missing = [str(path) for path in tables.values() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Text2SQL local CSV files are missing: " + ", ".join(missing)
        )
    output = output.expanduser()
    if not output.is_absolute():
        output = root / output
    if output.exists() and not overwrite:
        raise FileExistsError(f"{output} already exists. Pass --overwrite to replace it.")
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        output.unlink()
    connection = sqlite3.connect(output)
    try:
        for table, csv_path in tables.items():
            _load_csv_table(connection, table, csv_path)
        connection.commit()
    finally:
        connection.close()
    return output


def write_text2sql_env_file(*, root: Path, database_path: Path, env_file: Path) -> Path:
    env_file = env_file.expanduser()
    if not env_file.is_absolute():
        env_file = root / env_file
    env_file.parent.mkdir(parents=True, exist_ok=True)
    database_path = database_path.resolve()
    env_file.write_text(
        "\n".join(
            [
                "# Generated by uv run agentweave-prepare-text2sql.",
                "# Loaded automatically by AgentWeave server and Streamlit startup.",
                "TEXT2SQL_BACKEND=sqlite",
                f"TEXT2SQL_DATABASE_URL=sqlite:///{database_path}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return env_file


def manifest_csv_tables(*, root: Path, manifest: Any) -> dict[str, Path]:
    """Resolve local CSV files for Text2SQL prepare-time SQLite generation."""
    data_root = root / "subagents" / "text2sql" / "data"
    return {
        domain.table: data_root / f"{domain.table}.csv"
        for domain in Text2SQLDomainCatalog.from_agent(manifest).list_domains()
    }


def _load_csv_table(connection: sqlite3.Connection, table: str, csv_path: Path) -> None:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = [dict(row) for row in reader]
        columns = list(reader.fieldnames or [])
    if not columns:
        raise ValueError(f"CSV file has no header: {csv_path}")
    column_types = {
        column: _infer_sqlite_type([row.get(column, "") for row in rows])
        for column in columns
    }
    column_sql = ", ".join(
        f"{quote_identifier(column)} {column_types[column]}"
        for column in columns
    )
    connection.execute(f"CREATE TABLE {quote_identifier(table)} ({column_sql})")
    placeholders = ", ".join("?" for _ in columns)
    insert_sql = (
        f"INSERT INTO {quote_identifier(table)} "
        f"({', '.join(quote_identifier(column) for column in columns)}) "
        f"VALUES ({placeholders})"
    )
    connection.executemany(
        insert_sql,
        (
            [_coerce_value(row.get(column, ""), column_types[column]) for column in columns]
            for row in rows
        ),
    )


def _infer_sqlite_type(values: list[str]) -> str:
    non_empty = [str(value).strip() for value in values if str(value).strip()]
    if non_empty and all(_is_int(value) for value in non_empty):
        return "INTEGER"
    if non_empty and all(_is_float(value) for value in non_empty):
        return "REAL"
    return "TEXT"


def _coerce_value(value: Any, sqlite_type: str) -> Any:
    text = str(value).strip() if value is not None else ""
    if text == "":
        return None
    if sqlite_type == "INTEGER":
        return int(text)
    if sqlite_type == "REAL":
        return float(text)
    return str(value)


def _is_int(value: str) -> bool:
    try:
        int(value)
        return True
    except ValueError:
        return False


def _is_float(value: str) -> bool:
    try:
        float(value)
        return True
    except ValueError:
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare Text2SQL local SQLite DB.")
    parser.add_argument("--root", default=".", help="AgentWeave backend project root.")
    parser.add_argument(
        "--output",
        default=".agentweave/text2sql.sqlite",
        help="SQLite database output path.",
    )
    parser.add_argument("--overwrite", action="store_true", help="Replace existing DB file.")
    parser.add_argument(
        "--env-file",
        default=".agentweave/text2sql.env",
        help="Env file to write with TEXT2SQL_BACKEND and TEXT2SQL_DATABASE_URL.",
    )
    parser.add_argument(
        "--no-env-file",
        action="store_true",
        help="Prepare the database without writing a runtime env file.",
    )
    args = parser.parse_args()
    root = Path(args.root).resolve()
    output = prepare_sqlite_database(
        root=root,
        output=Path(args.output),
        overwrite=bool(args.overwrite),
    )
    print(f"prepared={output}")
    if not args.no_env_file:
        env_file = write_text2sql_env_file(
            root=root,
            database_path=output,
            env_file=Path(args.env_file),
        )
        print(f"env_file={env_file}")
    print("next=uv run agentweave-server")


if __name__ == "__main__":
    main()
